# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13f53b4a61396623c99d0c026e9f9a0d696ef1a6c368066b8706352d5baf46875451591d06bfc6c584cab8b69c7347b09b47cb2aa741df115206a47ef4fa9949

test:
  secret_key_base: 49c72bcc6cf023617746ef7344be2a9381333dab3b0c7be26a5dc8dc891974ac46bc18225727edbda2610a3040a43d7b708d7e68f4e1e2f8870958dfb7443be5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
